services:
  app:
    build: .
    container_name: wpp_laptop_app
    ports:
      - "8900:8900"
    volumes:
      - mongodb_data:/data/db
      - app_data:/app/applications
    restart: unless-stopped

volumes:
  mongodb_data:
  app_data:
